export const DEFAULT_TILE_WIDTH = 64;
export const DEFAULT_TILE_HEIGHT = 32;
export const TERRAIN_TILE_PADDING = 6;

export const BUILDING_SPRITE_WIDTH = 160;
export const BUILDING_SPRITE_HEIGHT = 160;

export const COLONIST_SPRITE_WIDTH = 24;
export const COLONIST_SPRITE_HEIGHT = 30;

export const DEFAULT_BUILDING_THUMBNAIL_SIZE = 56;
export const DEFAULT_RESOURCE_ICON_SIZE = 20;

export const PREWARM_TERRAIN_GRASS_VARIANTS = 4;
export const PREWARM_COLONIST_FRAME_COUNT = 3;

