export const BUILDING_CATEGORIES = [
  'housing',
  'production',
  'infrastructure',
  'culture',
  'defense',
];

export const BUILDING_DEFINITIONS = {
  hut: {
    id: 'hut',
    name: 'Hut',
    category: 'housing',
    color: 0x8b5a2b,
    size: [2.1, 1.7, 2.1],
    cost: { wood: 32 },
    buildTime: 7,
    populationCap: 3,
    moraleBonus: 1,
  },
  house: {
    id: 'house',
    name: 'House',
    category: 'housing',
    color: 0xc08457,
    size: [2.8, 2.2, 2.8],
    cost: { wood: 58, stone: 20 },
    buildTime: 11,
    populationCap: 6,
    moraleBonus: 2,
    requiredTech: 'masonry',
  },
  apartment: {
    id: 'apartment',
    name: 'Apartment',
    category: 'housing',
    color: 0x94a3b8,
    size: [3.2, 3.8, 3.2],
    cost: { wood: 90, stone: 70, tools: 8 },
    buildTime: 18,
    populationCap: 11,
    moraleBonus: 3,
    requiredTech: 'engineering',
  },
  farm: {
    id: 'farm',
    name: 'Farm',
    category: 'production',
    color: 0x65a30d,
    size: [3.8, 0.9, 3.8],
    cost: { wood: 45, stone: 16 },
    buildTime: 10,
    workerSlots: 3,
    preferredJob: 'farmer',
    outputPerWorker: { food: 2.1 },
  },
  lumberCamp: {
    id: 'lumberCamp',
    name: 'Lumber Camp',
    category: 'production',
    color: 0x854d0e,
    size: [3.2, 1.7, 3.2],
    cost: { wood: 35, stone: 12 },
    buildTime: 9,
    workerSlots: 2,
    preferredJob: 'lumberjack',
    outputPerWorker: { wood: 1.9 },
  },
  quarry: {
    id: 'quarry',
    name: 'Quarry',
    category: 'production',
    color: 0x64748b,
    size: [3.3, 2.1, 3.3],
    cost: { wood: 38, stone: 20 },
    buildTime: 12,
    workerSlots: 2,
    preferredJob: 'miner',
    outputPerWorker: { stone: 1.5 },
  },
  ironMine: {
    id: 'ironMine',
    name: 'Iron Mine',
    category: 'production',
    color: 0x4b5563,
    size: [3.3, 2.4, 3.3],
    cost: { wood: 55, stone: 30, tools: 4 },
    buildTime: 14,
    workerSlots: 2,
    preferredJob: 'miner',
    outputPerWorker: { iron: 1.15 },
    requiredTech: 'deep-mining',
  },
  workshop: {
    id: 'workshop',
    name: 'Workshop',
    category: 'production',
    color: 0x7e22ce,
    size: [3.4, 2.1, 3.4],
    cost: { wood: 64, stone: 25 },
    buildTime: 13,
    workerSlots: 2,
    preferredJob: 'artisan',
    inputPerWorker: { wood: 0.7, iron: 0.5 },
    outputPerWorker: { tools: 0.45 },
    requiredTech: 'smithing',
  },
  clinic: {
    id: 'clinic',
    name: 'Clinic',
    category: 'infrastructure',
    color: 0xdb2777,
    size: [3.1, 2, 3.1],
    cost: { wood: 75, stone: 30, tools: 6 },
    buildTime: 15,
    workerSlots: 1,
    preferredJob: 'medic',
    inputPerWorker: { food: 0.35, knowledge: 0.22 },
    outputPerWorker: { medicine: 0.2 },
    moraleBonus: 1,
    requiredTech: 'medicine',
  },
  warehouse: {
    id: 'warehouse',
    name: 'Warehouse',
    category: 'infrastructure',
    color: 0x78350f,
    size: [4.5, 2.7, 4.5],
    cost: { wood: 70, stone: 35 },
    buildTime: 12,
    storageCap: 260,
  },
  school: {
    id: 'school',
    name: 'School',
    category: 'culture',
    color: 0x2563eb,
    size: [3.8, 2.5, 3.8],
    cost: { wood: 70, stone: 28 },
    buildTime: 13,
    workerSlots: 2,
    preferredJob: 'scholar',
    outputPerWorker: { knowledge: 0.95 },
    moraleBonus: 2,
  },
  library: {
    id: 'library',
    name: 'Library',
    category: 'culture',
    color: 0x1d4ed8,
    size: [4.3, 2.9, 4.3],
    cost: { wood: 90, stone: 40, tools: 6 },
    buildTime: 18,
    workerSlots: 2,
    preferredJob: 'scholar',
    outputPerWorker: { knowledge: 1.35 },
    moraleBonus: 3,
    requiredTech: 'civil-service',
  },
  shrine: {
    id: 'shrine',
    name: 'Shrine',
    category: 'culture',
    color: 0x14b8a6,
    size: [2.4, 2.8, 2.4],
    cost: { wood: 40, stone: 25 },
    buildTime: 9,
    moraleBonus: 4,
  },
  watchtower: {
    id: 'watchtower',
    name: 'Watchtower',
    category: 'defense',
    color: 0x334155,
    size: [2.1, 4.5, 2.1],
    cost: { wood: 45, stone: 30 },
    buildTime: 10,
    moraleBonus: 1,
  },
};

export const STARTING_BUILDINGS = [
  { type: 'hut', x: -4, z: -3 },
  { type: 'farm', x: 5, z: -2 },
  { type: 'lumberCamp', x: -8, z: 4 },
  { type: 'quarry', x: 6, z: 6 },
  { type: 'school', x: -1, z: 4 },
];
