export const RESEARCH_DEFINITIONS = {
  masonry: {
    id: 'masonry',
    name: 'Masonry',
    description: 'Unlock sturdy houses and improved stone construction.',
    cost: 40,
    time: 40,
    prerequisites: [],
  },
  'deep-mining': {
    id: 'deep-mining',
    name: 'Deep Mining',
    description: 'Unlock iron mines for advanced industry.',
    cost: 60,
    time: 55,
    prerequisites: ['masonry'],
  },
  smithing: {
    id: 'smithing',
    name: 'Smithing',
    description: 'Unlock workshops to craft tools.',
    cost: 65,
    time: 50,
    prerequisites: ['deep-mining'],
  },
  medicine: {
    id: 'medicine',
    name: 'Medicine',
    description: 'Unlock clinics and improve health resilience.',
    cost: 90,
    time: 60,
    prerequisites: ['smithing'],
  },
  'civil-service': {
    id: 'civil-service',
    name: 'Civil Service',
    description: 'Unlock libraries and accelerate scientific growth.',
    cost: 110,
    time: 70,
    prerequisites: ['medicine'],
  },
  engineering: {
    id: 'engineering',
    name: 'Engineering',
    description: 'Unlock apartments and long-term expansion.',
    cost: 140,
    time: 80,
    prerequisites: ['civil-service'],
  },
  'colony-charter': {
    id: 'colony-charter',
    name: 'Colony Charter',
    description: 'Finalize the colony governance blueprint.',
    cost: 180,
    time: 95,
    prerequisites: ['engineering'],
  },
};
